services:
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /tmp/minio --console-address ":9001"
        volumes:
            - ./data/minio:/mnt/data
        env_file:
            - "./setup/minio/config.env"

    postgres:
        image: postgres:15
        container_name: postgres
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        env_file:
            - "./setup/postgres/config.env"

    adminer:
        image: adminer:5.4.2
        container_name: adminer_db_manager
        ports:
            - 8080:8080
